### ISSUE TITLE
Need a proper link to CarpentryCon 2018, Dublin, Ireland

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#10]
carpentrycon.org will always be used by the current CarpentryCon - we need a way to link to past events

**Comment by BinxiePeterson** [comment]
@anenadic for the time being I added the http://www.carpentrycon.org/ link on our current website (pending merging of pull request) so that people can refer to the 2018 website.

**Comment by anenadic** [comment]
I have actually added a portion of the new website dedicated to past CarpentryCons but have forgotten to close this issue. There is a separate issue to point  http://www.carpentrycon.org/ to https://carpentrycon.github.io/carpentrycon2020/ (see #18 ) once we are ready to release the new website, thanks @BinxiePeterson

**Comment by anenadic** [comment]
@BinxiePeterson Actually, the link to CarpentryCon 2018 should be https://carpentrycon.github.io/carpentrycon2018/ which should be working once we switch the DN. I am going to accept the PR https://github.com/carpentrycon/carpentrycon2020/pull/15 and then fix this.
