### ISSUE TITLE
Fix Task Force members

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#24]
The up-to-date list is at:
https://github.com/carpentries/carpentrycon as per @malvikasharan's comment.

**Comment by anenadic** [comment]
This list (https://github.com/carpentries/carpentrycon) does not seem to be up to date @malvikasharan, @serahrono sent me more details in an email: 



1. Website and Outreach (incl merchandise)

    Serah Rono (staff liaison)


2. Communication

    Serah Rono (staff liaison)


3. Budget  

    Sher! (staff liason)
    Serah Rono (staff liaison)
    Elizabeth Williams (staff liaison)


4. Program

    Sher! (Staff Liason)


5. Content development 

    Sher! (Co-chair)
    Serah Rono (staff liaison)

 

6. Accessibility 

    Sher! (Staff liason)

**Comment by anenadic** [comment]
OK, I have added some fixes (see f19c9a434909d1263f707fd16895f8d701e89bbc), needs checking if this is OK and also carpentrycon repo needs fixing, see: https://github.com/carpentries/carpentrycon/issues/146

**Comment by sheraaronhurt** [comment]
@anenadic for Content Development I am also a staff liason :)

**Comment by sstevens2** [comment]
I'm not on the program committee any more (too many other committees to meet with).

**Comment by anenadic** [comment]
Thx @sstevens2 , fixed via df33dc9e4276dbc7e1e2dd6314840c1b0ddca133
