### ISSUE TITLE
Fix z-index on tabs/menu on small screens

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#32]

**Comment by anenadic** [comment]
After a bit of investigation - this does not appear to be z-index issue - there seems to be something wrong with the menu not being clickable on home page only - e.g. see also issue #40 and font weight is also different on front page (it gets bold than flickers back to thin on home page only).

**Comment by fmichonneau** [comment]
I think I fixed this with https://github.com/carpentrycon/carpentrycon2020/commit/7ca15b74b57bf1cd17b237a0f72b9f3d40cfdef6

**Comment by anenadic** [comment]
Ah, it was a z-index issue after all - I can confirm that the drop down menu on small screens is now clickable @fmichonneau. Closing this issue.
