### ISSUE TITLE
Font too thin

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#35]
Some feedback recieved via slack:

Hi all! I received some feedback recently that the contrast on the CarpentryCon website font isn’t quite high enough (the font is very thin), making it very hard to read for someone with less-than-perfect vision. Would it be possible to improve this when there’s a chance? Thank you!

**Comment by anenadic** [comment]
@sstevens2  if this for the new website? Because I have recently improved the contrast with background and text.

**Comment by anenadic** [comment]
So I saw @serahrono fix for this but for me it does not seem to show on index - the bolder font appears and then it disappears. Other pages are fine. Anyone else noticing this @sstevens2 @serahrono  ?

**Comment by sstevens2** [comment]
The main page does seem to load and very briefly appear bold and then return to the the thinner font.  The other pages do appear bold too. 

I think this was for the new website.  The comment came in the Monday after we had swapped.

**Comment by anenadic** [comment]
I have already contacted Francois earlier today again (privately) - the thing with the flashing bold-thin font on index I believe comes from some caching issue on the server @sstevens2. Also some other fixes I committed earlier today are not showing up which led me to believe the site is again affected by caching problems. I do not have access to AWS cloud where site is hosted but I believe Francois will have a look at it.

**Comment by sstevens2** [comment]
Ahh, that would make sense.  Good to know.

**Comment by anenadic** [comment]
@sstevens2 Francois did have a look at it just now - I suggest we leave it for the next day or so and see if it sorts itself out with clearing the cache. The site is a bit unstable with the flurry of modifications but hopefully it will stabilise soon.

**Comment by fmichonneau** [comment]
this should also be fixed now. It's not available on the main domain quite yet but it's visible here http://2020.carpentrycon.org.s3-website-us-east-1.amazonaws.com/
