### ISSUE TITLE
Find where it is located and fix link to AtoZ_of_CarpentryCon

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#4]

**Comment by anenadic** [comment]
https://github.com/carpentries/carpentrycon2020/blob/master/AtoZ_of_CarpentryCon.md not working

**Comment by BinxiePeterson** [comment]
Here is the link to CarpentryCon 2018 A-Z .md file https://github.com/carpentries/carpentrycon/blob/master/AtoZ_of_CarpentryCon.md

**Comment by anenadic** [comment]
Thx @BinxiePeterson. Closing via 7d879d43.
