### ISSUE TITLE
Navigation bar disappears from homepage on scroll

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#40]
From @serahrono: In Safari, the navigation bar disappears from homepage on scroll, but remains Sticky, as expected on Chrome.

From @fmichonneau: probably related, on Firefox the navigation bar is still visible but it's not possible to click on the items. This happens once scrolling past "Why attend CarpentryCon?"

**Comment by anenadic** [comment]
I think I have fixed the issue pointed out by @fmichonneau that in Firefox the navigation bar links are visible but not clickable - the issue was with z-index - see 51f2b53b6eb6286435a5fdb9469148b1f5bd781b.

The issue that on Safari sticky navigation bar disappears only now seems to happen on index page - probably something with the design of the "tiles" on front page is causing this. Posisbly z-index again somewhere.

**Comment by anenadic** [comment]
After a bit of investigation, there seems to be something wrong on home page only - e.g. see issue #32 which also happens only on home page and not on other pages.

**Comment by fmichonneau** [comment]
I can confirm I don't see this anymore on Firefox.

**Comment by anenadic** [comment]
The issue only now happens on Safari and only on home page. Firefox, Chrome and small devices all seem to be OK.

**Comment by anenadic** [comment]
I propose to close this issue as most browsers seem OK.
