### ISSUE TITLE
fix jumbotron on medium screens

### ISSUE THREAD

**Issue by fmichonneau** [carpentrycon/carpentrycon2020#46]
![Screen Shot 2019-11-26 at 12 34 03](https://user-images.githubusercontent.com/5502922/69658166-b1363c00-1049-11ea-89fc-f43099e5c408.png)

**Comment by anenadic** [comment]
Think I managed to fix this on various size screens, worth testing more @fmichonneau. See  853a30cf752584bcef6668e2fe3f23c12ae77b8a.
