### ISSUE TITLE
moving text is distracting?

### ISSUE THREAD

**Issue by fmichonneau** [carpentrycon/carpentrycon2020#47]
I find that having the effect of the location for the conference to come in and out is distracting, and it might cause confusion about the exact location for the venue. It's probably not great for screen readers, and it makes the responsiveness of the formatting challenging.

**Comment by HaoZeke** [comment]
Seconded. Marquees are generally a bad idea. Maybe a pop-up?

**Comment by anenadic** [comment]
TBH I do not like it either, it came with the theme. I am just going to change it to be a good old-fashioned static text @fmichonneau @HaoZeke.
