### ISSUE TITLE
New form for expressing sponsorship interest needed

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#6]
Old form from 2018: "https://docs.google.com/forms/d/e/1FAIpQLSedlt68CXVmyVJ4DEI8P9nfAXhGYbTHA9YgFQYomXjzzZDJOg/viewform"

**Comment by BinxiePeterson** [comment]
I found this form in our CarpentryCon 2020 Google Drive https://forms.gle/ToQiXu96k3d2Zg8s5 - I also added this link (pending merging of pull request) to our current website. I'll confirm with Sher! whether this is the correct form to be used.
