### ISSUE TITLE
add accessibility information

### ISSUE THREAD

**Issue by ChristinaLK** [carpentrycon/carpentrycon2020#63]
Will try to have this ready over the weekend!

**Comment by ChristinaLK** [comment]
Written! Just sent an email asking for final edits. Should be able to be posted this week.

**Comment by ChristinaLK** [comment]
This is ready to go. Sher suggested this go in a separate tab? 

https://docs.google.com/document/d/12K3y6JoYSgzABzRAtVwD6PQGgQTG2IxL9BE7hgGBeBQ/edit

**Comment by anenadic** [comment]
Added a separate page for accessibility and linked to travel & venue and the other way around @ChristinaLK.
