### ISSUE TITLE
Assign people to monitor carpentrycon@carpentries.org

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#7]

**Comment by sstevens2** [comment]
Not sure how these emails come in but as member/co-chair of the communications committee, I'd be happy to help or even take the lead on emails coming in there.

**Comment by anenadic** [comment]
Thank @sstevens2 - we'd need a few people to look after this so that you are not overloaded and also when you go on leave :-). @serahrono do we know who controls this mailing list and can we add more members?
