### ISSUE TITLE
Add missing task force members photos

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#71]

**Comment by anenadic** [comment]
From Bianca: Missing TF pictures: Jessica, Mina, Fotis, Danielle, Mark

**Comment by annefou** [comment]
Ok. I'll contact them again but I think to remember that some of them do not want to have their picture.

**Comment by anenadic** [comment]
Yes, that's right - thought we have done them all. There is a related issue to add E. Wickes to one of the subcommittees and put Sateesh under Alumni #70 .
