### ISSUE TITLE
Update T-shirt competition deadline

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#72]
End of Feb is the new deadline

**Comment by ChristinaLK** [comment]
Or did we decide on mid-March?

**Comment by annefou** [comment]
We moved the deadline to 20th March and I updated the website.

**Comment by anenadic** [comment]
Yes, March - I did not update the issue but have updated the website too, without seeing that Anne did it too :-).

**Comment by anenadic** [comment]
I've also added a button at the top for more prominence
