### ISSUE TITLE
Comment out most of the content

### ISSUE THREAD

**Issue by anenadic** [carpentrycon/carpentrycon2020#83]
- [x] leave home page and message about cancellation
- [x] leave blog/news
- [x] comment out all other tabs

**Comment by ChristinaLK** [comment]
Also remove all the buttons under the header?

**Comment by anenadic** [comment]
Which buttons @ChristinaLK? This is what I see - changes may have propagated for you just yet.
![image](https://user-images.githubusercontent.com/631719/79462325-3cab6c00-7fef-11ea-8c7d-11530568cff8.png)

**Comment by ChristinaLK** [comment]
that looks good! I think that was an old note.
